### ISSUE TITLE
Bug in utils/create_point_cloud_from_touches.py

### ISSUE THREAD

**Issue by ZuoJiaxing** [armlabstanford/Touch-GS#1]
File "utils/create_point_cloud_from_touches.py", line 52, in get_point_cloud_from_depth_and_color
    color = color_image[v, u]
IndexError: index 720 is out of bounds for axis 0 with size 720

I checked the code,  color_image is with shape (720, 1280, 3), while depth_image is with shape (1280, 720)

**Comment by peasant98** [comment]
Hi @ZuoJiaxing, thanks for checking out our work! I re-ran our pipeline and was able to replicate the bug; I committed the fix (https://github.com/armlabstanford/Touch-GS/commit/1619bcfd02ada50c8ae6c6db676ffb533b069537) and it should work from your end. Please let us know if you run into any other issues/have any questions!

**Comment by peasant98** [comment]
Hi @ZuoJiaxing, wanted to check in -- were you able to get it fixed?

**Comment by peasant98** [comment]
Closing this as it seems fixed for now.
